version: '3.0'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: Constantine@2016
  redis:
    image: redis
    ports:
      - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
      xpack.security.enabled : false
      discovery.type :  single-node
    ports:
      - 9200:9200

  chat-system-service:
    restart: always
    ports:
      - "3000:3000"
    depends_on:
         - mysql
         - redis
    build: ./
    image: chat-system-api
    container_name: chat-system-api




