version: '3.0'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: Constantine@2016
  redis:
    image: redis
    ports:
      - 6379:6379
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      discovery.type :  single-node
    ports:
      - 9200:9200
  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - 5672:5672
        - 15672:15672
  chat-system-service:
    restart: always
    ports:
      - "3000:3000"
    depends_on:
         - mysql
         - rabbitmq
    build: ./
    image: chat-system-api
    container_name: chat-system-api
    environment:
       SERVER_HOST_NAME : chat-system-service
  
  chat-client-service:
    restart: always
    ports:
      - "3001:3000"
    depends_on:
         - chat-system-service
         - redis
    build: ./chatMessageCreationClientApi
    image: chat-client-api
    container_name: chat-client-api







